**09/05**

OH: Thursdays 2-3p; CDS 441

**Next Week**

* Read integrate fire papers

* no class/OHs 09/12

In [25]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Open and read csv locally
df = pd.read_csv("~/Desktop/CASMA665/09.05/Rhythms_1.csv")


In [26]:
# create array of 10 zeros using numpy
# more standard
import numpy as np
arr = np.zeros(10)
print(arr)

from numpy import *  # import all from numpy
arr = zeros(10)
print(arr)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Another Ex

In [30]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr)
print(arr*arr)
print(arr.shape)
print(np.shape(arr))
print(arr[0])
print(arr[-1])

b = 3*arr
print("b=", b)

c = np.array([arr,b])
print(c)
print("print first row: ", c[0,:])
print(np.shape(c))
print("last column", c[:,-1])


[1 2 3 4]
[ 1  4  9 16]
(4,)
(4,)
1
4
b= [ 3  6  9 12]
[[ 1  2  3  4]
 [ 3  6  9 12]]
print first row:  [1 2 3 4]
(2, 4)
last column [ 4 12]


#### Challenge
Find all vals in c greater than or equal to 5, and set them to 0. Call this new variable d.


In [33]:
# print(c)
# print(c>5)

for rows in np.arange(np.shape(c)[0]):
    for cols in np.arange(np.shape(c)[1]):
        if c[rows,cols] >= 5:
            c[rows,cols] = 0
print(c)


[[1 2 3 4]
 [3 0 0 0]]


In [35]:
import numpy as np
c = np.array([[1, 2, 3, 4],[3, 6, 9, 12]])
c[c>=5] = 0
d = c
print(d)


[[1 2 3 4]
 [3 0 0 0]]


#### Challenge!!

Write a function that takes two inputs (each a number) and returns their squared sum.


In [38]:
"""
Description
Function that takes in 2 inputs and returns their squared sum.

Args:
a --- first value
b --- second value to add to first, then square together

Returns:
numerical value of squared sum

Example:
"""

def sq(a, b):
    return a**2 + b**2

print(sq(2, 10))

104
